### ISSUE TITLE
Endpoints no longer exist?

### ISSUE THREAD

**Issue by gouinK** [nixonjoshua98/dexscreener#1]
Greetings, it seems like this endpoint does not exist anymore:
"https://io6.dexscreener.io/u/trading-history/recent/{network}/{address}"

Is this true or am I doing something wrong? If it is true, do you know of an updated endpoint to accomplish the same task?

Thanks!

**Comment by nixonjoshua98** [comment]
Hi,

That endpoint was an 'unofficial' endpoint I had gotten while looking around the site. It looks like it has moved to 'https://io.dexscreener.com/u/trading-history/{network}/{address}' but they have added CloudFare protection so i'm going to unfortunately have to remove it from this package until they support it again .

**Comment by nixonjoshua98** [comment]
Looks like they have added protection for the bar chart endpoint as well, so will have to remove that as well.

**Comment by nixonjoshua98** [comment]
Update (to remove endpoints) - `pip install dexscreener==0.2`

**Comment by gouinK** [comment]
Got it, ok that makes sense. So there are no other endpoints on their site to get transaction histories?
I was finding it really hard to extract any useful information from their API documentation (https://docs.dexscreener.com/), so I was really glad when I found your package.

**Comment by nixonjoshua98** [comment]
Not yet. Hopefully they add one at some point
