### ISSUE TITLE
Dexcreener API update

### ISSUE THREAD

**Issue by Jarki** [nixonjoshua98/dexscreener#10]
Looking at [Dexscreener API reference](https://docs.dexscreener.com/api/reference), it looks like they made some changes that are not yet reflected in this SDK.

Namely, here are the changes:

1. New methods:
- Get the latest token profiles
- Get the latest boosted tokens
- Get the tokens with most active boosts
- Check orders paid for of token
2. Base URL changed (https://api.dexscreener.io -> https://api.dexscreener.com) (Note: https://api.dexscreener.io still works, but it redirects to .com)
3. Rate limits on existing methods changed from 100 requests per minute to 300

Since I needed one of the methods for my project, I decided to create a fork and implement it myself. I created a new class, which contains all the new methods, and also made some necessary changes to existing code. You can look at the code [here](https://github.com/Jarki/dexscreener). If you think this implementation works for the project, I’d be happy to open a pull request!

**Comment by nixonjoshua98** [comment]
Hi, looks good! I haven't seen the 'str|None' syntax before, is this available in 3.9? If it is then keep it, or switch to Optional so we can keep a lower python requirement please

**Comment by Jarki** [comment]
Yes, looks like this syntax is only available in 3.10+. I changed everything to Optional and tested in a 3.9 environment, got no errors
