### ISSUE TITLE
What is volume data?

### ISSUE THREAD

**Issue by yohplala** [nixonjoshua98/dexscreener#12]
I am sorry to ask this here, this is not necessarily specific to your project, but I was hoping to find an answer.
You have implemented in models.py

```python
class VolumeChangePeriods(_TimePeriodsFloat):
    ...

class TokenPair(BaseModel):
    volume: VolumeChangePeriods
```

I am not a python expert, what does mean the 3 dots that are in the code?
Also, do you know what is this ``volume`` data? You mention "volume change", is it transaction volume? If yes, over which period and which unit (USD?)?

Thanks a lot for your help!

**Comment by nixonjoshua98** [comment]
M being minutes and H being hours so 5m is 5mins etc. ... just means empty

**Comment by nixonjoshua98** [comment]
Id refer to the API documentation for any property questions

**Comment by yohplala** [comment]
Hi, thanks great, my question was probably silly.
Maybe still a last one. Do you know the unit? Is it USD or quote token or base token?
