### ISSUE TITLE
Async Client

### ISSUE THREAD

**Issue by mikulas-mrva** [nixonjoshua98/dexscreener#2]
Do you have any plans to add asyncio support to this SDK? 

It looks fairly easy to do as the code is quite straightforward so far, and would be a massive help for many projects, I'm sure.

**Comment by mikulas-mrva** [comment]
(having a second look, `RateLimiter` looks a wee bit trickier to migrate to async)

**Comment by nixonjoshua98** [comment]
HI, I have added `_async` versions of each methods. I've also updated the rate limiter to work as async (not perfect but the rate limits are pretty high on the API so not too worried about it)

**Comment by nixonjoshua98** [comment]
https://pypi.org/project/dexscreener/0.3/ should be available which has async support - Let me know if you have issues
